package com.myspace.test_git_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long empId;

	public Employee() {
	}

	public java.lang.Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(java.lang.Long empId) {
		this.empId = empId;
	}

	public Employee(java.lang.Long empId) {
		this.empId = empId;
	}

}