package com.myspace.test_git_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long empId;

	private java.lang.String empName;

	private java.lang.String empDesig;

	public Employee() {
	}

	public java.lang.Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(java.lang.Long empId) {
		this.empId = empId;
	}

	public java.lang.String getEmpName() {
		return this.empName;
	}

	public void setEmpName(java.lang.String empName) {
		this.empName = empName;
	}

	public java.lang.String getEmpDesig() {
		return this.empDesig;
	}

	public void setEmpDesig(java.lang.String empDesig) {
		this.empDesig = empDesig;
	}

	public Employee(java.lang.Long empId, java.lang.String empName,
			java.lang.String empDesig) {
		this.empId = empId;
		this.empName = empName;
		this.empDesig = empDesig;
	}

}